import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import samples from '../lib/samples.json';
import {buildMesh,renderSet,DEFAULT_STYLE,clone,RENDERER_VERSION,type Model} from '../lib/pixel';
import type {AnimationDocument} from '../lib/animation';
const origin=process.env.TEST_ORIGIN||'http://localhost:5173';
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');assert.ok(cookie);
async function call(path:string,data?:unknown,auth=cookie){const r=await fetch(origin+path,{method:data?'POST':'GET',headers:{...(auth?{cookie:auth}:{}),...(data?{'Content-Type':'application/json',Origin:origin}:{})},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json() as any};}
assert.equal((await call('/api/animations?assetId=missing',undefined,'')).status,401);
const projectId=crypto.randomUUID(),assetId=crypto.randomUUID(),revisionId=crypto.randomUUID();
const style={...clone(DEFAULT_STYLE),id:crypto.randomUUID()};
const p=await call('/api/studio',{action:'project',project:{id:projectId,name:'アニメーション統合検証',styles:[style],version:0,updatedAt:''}});assert.equal(p.status,200,JSON.stringify(p.data));
const m=samples[0] as Model,frames=renderSet(buildMesh(m),style);
const revision={id:revisionId,rendererVersion:RENDERER_VERSION,createdAt:new Date().toISOString(),style,frames,baseFrames:clone(frames),approved:false,reviewed:false,issues:'',mode:'eight',source:'sample',modelId:m.id,name:m.name,prompt:m.prompt,features:m.features,facing:0,size:1};
const asset=await call('/api/studio',{action:'asset',asset:{id:assetId,projectId,name:m.name,revisions:[revision],version:0,updatedAt:''}});assert.equal(asset.status,200,JSON.stringify(asset.data));
const baked=JSON.parse(readFileSync('/private/tmp/dotforge-animation-verification/document.json','utf8')) as AnimationDocument;
const document={...baked,id:crypto.randomUUID(),assetId,sourceRevisionId:revisionId,config:{...baked.config,style}};
const saved=await call('/api/animations',document);assert.equal(saved.status,200,JSON.stringify(saved.data));assert.equal(saved.data.version,1);
assert.equal((await call('/api/animations',document)).status,409,'古い版を拒否');
const loaded=await call('/api/animations?id='+document.id);assert.equal(loaded.status,200);assert.deepEqual(loaded.data.baked,document.baked);assert.deepEqual(loaded.data.config,document.config);
const list=await call('/api/animations?assetId='+assetId);assert.equal(list.data.items[0].id,document.id);
assert.equal((await call('/api/animations?id='+document.id,undefined,'')).status,401);
assert.equal((await call('/api/animations',{...loaded.data,sourceRevisionId:'foreign'})).status,400);
const corrupt=clone(loaded.data);corrupt.baked[0].frames[0][0].body='b:AAAA';assert.equal((await call('/api/animations',corrupt)).status,400,'破損画像を拒否');
const unchecked=clone(loaded.data);unchecked.config.rig.reviewed=false;unchecked.reviewed=true;assert.equal((await call('/api/animations',unchecked)).status,400,'未確認リグの採用を拒否');
const adopted=await call('/api/animations',{...loaded.data,reviewed:true});assert.equal(adopted.status,200,JSON.stringify(adopted.data));
assert.equal((await call('/api/animations',{...adopted.data,name:'上書き'})).status,400,'採用版を保護');
const variant=await call('/api/animations',{...adopted.data,id:crypto.randomUUID(),version:0,reviewed:false});assert.equal(variant.status,200);
const staticAfter=await call('/api/studio?assetId='+assetId);assert.deepEqual(staticAfter.data.revisions[0].frames,frames,'元の静止画は変更されない');
writeFileSync('/private/tmp/dotforge-animation-test-records.json',JSON.stringify({projectId,assetId,animations:[document.id,variant.data.id]}));
console.log('アニメーションAPI: 保存・全画素復元・競合拒否・破損拒否・採用版保護・複製・静止画互換を検証。有料API送信0件。');
