import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import samples from '../lib/animal-samples.json';
import {buildMesh,renderSet,DEFAULT_STYLE,clone,RENDERER_VERSION} from '../lib/pixel';
import {ANIMAL_MOTION_VERSION,animalRig,animalClips,bakeAnimal,type AnimalConfig,type AnimalDocument} from '../lib/animal-animation';
import {parseAnimal} from '../lib/animal-contracts';
const origin=process.env.TEST_ORIGIN||'http://localhost:5173';
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');assert.ok(cookie);
async function call(path:string,data?:unknown,auth=cookie){const r=await fetch(origin+path,{method:data?'POST':'GET',headers:{...(auth?{cookie:auth}:{}),...(data?{'Content-Type':'application/json',Origin:origin}:{})},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json() as any};}
const projectId=crypto.randomUUID(),assetId=crypto.randomUUID(),revisionId=crypto.randomUUID(),jobId=crypto.randomUUID(),style={...clone(DEFAULT_STYLE),id:crypto.randomUUID()};
const created=await call('/api/studio',{action:'project',project:{id:projectId,name:'四足動物統合検証',styles:[style],version:0,updatedAt:''}});assert.equal(created.status,200,JSON.stringify(created.data));
writeFileSync('/private/tmp/dotforge-animal-test-records.json',JSON.stringify({projectId,assetId,jobId}));
const request={id:jobId,projectId,skillId:'animal',name:'検証用キツネ',prompt:'青い首輪のキツネ',features:['青い首輪'],mode:'eight',style,referenceKeys:[],referenceSides:[]};
assert.equal((await call('/api/generate',request)).status,200);
assert.equal((await call('/api/generate',request)).status,200);
const model=parseAnimal(samples[0]),artifact={kind:'rigged-quadruped-v1',skillVersion:'1.0.0',model,validation:{renderer:RENDERER_VERSION,motion:ANIMAL_MOTION_VERSION,frames:376,issues:[]},visualReview:'HTTP fixture persistence test; this text does not claim AI review.'};
assert.equal((await call('/api/generate',{action:'complete',id:jobId,artifact:{...artifact,kind:'rigged-humanoid-v1'}})).status,400,'人型成果を動物として受理しない');
assert.equal((await call('/api/generate',{action:'complete',id:jobId,artifact:{...artifact,validation:{...artifact.validation,frames:344}}})).status,400);
const tampered=clone(artifact);tampered.model.motionCorrections={frontPawL:[90,0,0]};assert.equal((await call('/api/generate',{action:'complete',id:jobId,artifact:tampered})).status,400,'四足の接地をサーバーで再検証');
const finished=await call('/api/generate',{action:'complete',id:jobId,artifact});assert.equal(finished.status,200,JSON.stringify(finished.data));assert.equal(finished.data.state,'ready');
assert.equal((await call('/api/generate',{action:'complete',id:jobId,artifact})).data.modelFile,finished.data.modelFile);
const stored=await call('/api/files?id='+finished.data.modelFile);assert.deepEqual(stored.data.model,model);
assert.equal((await call('/api/files?id='+finished.data.modelFile,undefined,'')).status,401);
const frames=renderSet(buildMesh(model),style),revision={id:revisionId,rendererVersion:RENDERER_VERSION,createdAt:new Date().toISOString(),style,frames,baseFrames:clone(frames),approved:false,reviewed:false,issues:'',mode:'eight',source:'skill',rigKind:'quadruped',modelId:model.id,modelKey:finished.data.modelFile,name:model.name,prompt:model.prompt,features:model.features,facing:0,size:1};
const savedAsset=await call('/api/studio',{action:'asset',asset:{id:assetId,projectId,name:model.name,revisions:[revision],version:0,updatedAt:''}});assert.equal(savedAsset.status,200,JSON.stringify(savedAsset.data));assert.equal(savedAsset.data.revisions[0].rigKind,'quadruped');
const config:AnimalConfig={version:ANIMAL_MOTION_VERSION,rig:animalRig(model),clips:animalClips(model.motionCorrections),scale:1,facing:0,style,mode:'eight'};
const document:AnimalDocument={id:crypto.randomUUID(),assetId,sourceRevisionId:revisionId,name:'四足の基本動作',config,baked:await bakeAnimal(buildMesh(model),config),version:0,updatedAt:'',reviewed:false};
const saved=await call('/api/animations',document);assert.equal(saved.status,200,JSON.stringify(saved.data));
assert.equal((await call('/api/animations',document)).status,409);
const loaded=await call('/api/animations?id='+document.id);assert.deepEqual(loaded.data.config,document.config);assert.deepEqual(loaded.data.baked,document.baked);
const adopted=await call('/api/animations',{...loaded.data,reviewed:true});assert.equal(adopted.status,200,JSON.stringify(adopted.data));
assert.equal((await call('/api/animations',{...adopted.data,name:'上書き'})).status,400);
const incompatible=await call('/api/studio',{action:'asset',asset:{...savedAsset.data,revisions:[{...revision,rigKind:'humanoid'}]}});assert.equal(incompatible.status,200);
assert.equal((await call('/api/animations',{...document,id:crypto.randomUUID()})).status,400,'素材の骨格種別が違えば拒否');
assert.equal((await call('/api/generate',{action:'consumed',id:jobId})).data.state,'consumed');
writeFileSync('/private/tmp/dotforge-animal-test-records.json',JSON.stringify({projectId,assetId,jobId,fileId:finished.data.modelFile,animations:[document.id]}));
console.log('Animal HTTP integration passed: skill routing, server motion revalidation, idempotency, authenticated persistence, rig kind, animation restore, CAS and adoption protection.');
