import assert from 'node:assert/strict';
import {DEFAULT_STYLE,clone,buildMesh,renderSet,type Model,type Revision} from '../lib/pixel';
import samples from '../lib/samples.json';
import {writeFileSync} from 'node:fs';
const origin=process.env.TEST_ORIGIN||'http://localhost:5174';
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookies=login.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
assert.ok(cookies,'ローカル認証cookieが得られる');
async function request(path:string,data?:unknown,cookie=cookies){const response=await fetch(origin+path,{method:data?'POST':'GET',headers:{...(cookie?{cookie}:{}),...(data?{'Content-Type':'application/json',Origin:origin}:{})},body:data?JSON.stringify(data):undefined});return {status:response.status,data:await response.json() as any};}
assert.equal((await request('/api/studio',undefined,'')).status,401);
const initial=await request('/api/studio');assert.equal(initial.status,200,JSON.stringify(initial.data));assert.equal(initial.data.providerReady,false,'本検証はキー未設定時だけ実行');
const id=crypto.randomUUID(),id2=crypto.randomUUID(),style={...clone(DEFAULT_STYLE),id:crypto.randomUUID()};
const p={id,name:'検証用プロジェクト（自動検証）',styles:[style],version:0,updatedAt:new Date().toISOString()};
const created=await request('/api/studio',{action:'project',project:p});assert.equal(created.status,200,JSON.stringify(created.data));assert.equal(created.data.version,1);
assert.equal((await request('/api/studio',{action:'project',project:p})).status,409,'古い版の更新を拒否');
const p2=await request('/api/studio',{action:'project',project:{...p,id:id2}});assert.equal(p2.status,200);
const model=samples[0] as Model,frames=renderSet(buildMesh(model),style);
const r:Revision={id:crypto.randomUUID(),createdAt:new Date().toISOString(),style,frames,baseFrames:clone(frames),approved:false,reviewed:false,issues:'',mode:'eight',source:'sample',modelId:model.id,features:model.features,name:model.name,prompt:model.prompt,facing:0,size:1};
const asset={id:crypto.randomUUID(),projectId:id,name:model.name,revisions:[r],version:0,updatedAt:new Date().toISOString()};
const saved=await request('/api/studio',{action:'asset',asset});assert.equal(saved.status,200,JSON.stringify(saved.data));assert.equal(saved.data.version,1);
const loaded=await request('/api/studio?assetId='+asset.id);assert.equal(loaded.status,200);assert.deepEqual(loaded.data.revisions[0].frames,frames,'R2保存・読込で全画素一致');
assert.equal((await request('/api/studio?assetId='+asset.id,undefined,'')).status,401);
assert.equal((await request('/api/studio',{action:'asset',asset:{...saved.data,projectId:id2}})).status,400,'所属プロジェクト変更を拒否');
const approved={...saved.data,revisions:[{...r,approved:true,reviewed:true}]};const adopted=await request('/api/studio',{action:'asset',asset:approved});assert.equal(adopted.status,200,JSON.stringify(adopted.data));
const changed=clone(adopted.data);changed.revisions[0].frames[0].body[32*64+32]=1;assert.equal((await request('/api/studio',{action:'asset',asset:changed})).status,400,'採用版の上書きを拒否');
const generation={id:crypto.randomUUID(),projectId:id,name:'API検証',prompt:'A small wooden chest',features:[],mode:'eight',style,referenceKeys:[],referenceSides:[],maxCredits:40,authorize:true,allowBackfill:true};
assert.equal((await request('/api/generate',{...generation,style:{...style,id:'foreign-style'}})).status,400,'保存済みでないスタイルで課金へ進まない');
assert.equal((await request('/api/generate',generation)).status,503,'キー未設定なら外部生成を呼ばない');
assert.equal((await request('/api/generate',{...generation,authorize:false})).status,400);
const final=await request('/api/studio?projectId='+id);assert.equal(final.data.jobs.length,0,'生成キー未設定でジョブや課金を作らない');
writeFileSync('/private/tmp/dotforge-local-test-records.json',JSON.stringify({projects:[id,id2],asset:asset.id}));
console.log('API統合検証: 認証、保存・復元、競合拒否、採用版保護、所属不変、生成前の検証、未設定キーの拒否を確認（有料API送信0件）');
