import assert from 'node:assert/strict';
import {DEFAULT_STYLE,clone,buildMesh,renderSet,type Model,type Revision} from '../lib/pixel';
import samples from '../lib/samples.json';
import {writeFileSync} from 'node:fs';
const origin=process.env.TEST_ORIGIN||'http://localhost:5174';
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookies=login.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
assert.ok(cookies,'ローカル認証cookieが得られる');
async function request(path:string,data?:unknown,cookie=cookies){const response=await fetch(origin+path,{method:data?'POST':'GET',headers:{...(cookie?{cookie}:{}),...(data?{'Content-Type':'application/json',Origin:origin}:{})},body:data?JSON.stringify(data):undefined});return {status:response.status,data:await response.json() as any};}
assert.equal((await request('/api/studio',undefined,'')).status,401);
const initial=await request('/api/studio');assert.equal(initial.status,200,JSON.stringify(initial.data));
const id=crypto.randomUUID(),id2=crypto.randomUUID(),style={...clone(DEFAULT_STYLE),id:crypto.randomUUID()};
const p={id,name:'検証用プロジェクト（自動検証）',styles:[style],version:0,updatedAt:new Date().toISOString()};
const created=await request('/api/studio',{action:'project',project:p});assert.equal(created.status,200,JSON.stringify(created.data));assert.equal(created.data.version,1);
assert.equal((await request('/api/studio',{action:'project',project:p})).status,409,'古い版の更新を拒否');
const p2=await request('/api/studio',{action:'project',project:{...p,id:id2}});assert.equal(p2.status,200);
const model=samples[0] as Model,frames=renderSet(buildMesh(model),style);
const r:Revision={id:crypto.randomUUID(),createdAt:new Date().toISOString(),style,frames,baseFrames:clone(frames),approved:false,reviewed:false,issues:'',mode:'eight',source:'sample',modelId:model.id,features:model.features,name:model.name,prompt:model.prompt,facing:0,size:1};
const asset={id:crypto.randomUUID(),projectId:id,name:model.name,revisions:[r],version:0,updatedAt:new Date().toISOString()};
const saved=await request('/api/studio',{action:'asset',asset});assert.equal(saved.status,200,JSON.stringify(saved.data));assert.equal(saved.data.version,1);
const loaded=await request('/api/studio?assetId='+asset.id);assert.equal(loaded.status,200);assert.deepEqual(loaded.data.revisions[0].frames,frames,'R2保存・読込で全画素一致');
assert.equal((await request('/api/studio?assetId='+asset.id,undefined,'')).status,401);
assert.equal((await request('/api/studio',{action:'asset',asset:{...saved.data,projectId:id2}})).status,400,'所属プロジェクト変更を拒否');
const approved={...saved.data,revisions:[{...r,approved:true,reviewed:true}]};const adopted=await request('/api/studio',{action:'asset',asset:approved});assert.equal(adopted.status,200,JSON.stringify(adopted.data));
const changed=clone(adopted.data);changed.revisions[0].frames[0].body[32*64+32]=1;assert.equal((await request('/api/studio',{action:'asset',asset:changed})).status,400,'採用版の上書きを拒否');
const generation={id:crypto.randomUUID(),projectId:id,skillId:'humanoid',name:'Skill検証',prompt:'港の修理技師',features:[],mode:'eight',style,referenceKeys:[],referenceSides:[]};
assert.equal((await request('/api/generate',{...generation,style:{...style,id:'foreign-style'}})).status,400,'保存済みでないスタイルを拒否');
assert.equal((await request('/api/generate',{...generation,skillId:'animal'})).status,400,'未登録skillを拒否');
const queued=await request('/api/generate',generation);assert.equal(queued.status,200,JSON.stringify(queued.data));assert.equal(queued.data.state,'queued');
assert.equal((await request('/api/generate',generation)).status,200,'同じIDの再送は重複しない');
assert.equal((await request('/api/generate',{...generation,prompt:'changed'})).status,409,'同じIDの別内容を拒否');
assert.equal((await request('/api/generate',{...generation,id:crypto.randomUUID()})).status,409,'同時生成の上限');
assert.equal((await request('/api/generate',{action:'complete',id:generation.id,artifact:{model:{}}})).status,400,'未検証モデルを拒否');
const {readFileSync}=await import('node:fs');const {parseHumanoid}=await import('../lib/generation');const modelData=parseHumanoid(JSON.parse(readFileSync('skills/dotforge-humanoid/references/scout.json','utf8')));
const artifact={kind:'rigged-humanoid-v1',skillVersion:'1.0.0',model:modelData,validation:{renderer:'orthographic-topdown-v2',motion:'humanoid-ik-v1',frames:344,issues:[]},visualReview:'HTTP persistence test fixture, not an AI quality claim'};
const tampered=clone(artifact);tampered.model.motionCorrections={footL:[90,0,0]};assert.equal((await request('/api/generate',{action:'complete',id:generation.id,artifact:tampered})).status,400,'報告が合格でも改変された動作をサーバーで再検証して拒否');
const finished=await request('/api/generate',{action:'complete',id:generation.id,artifact});assert.equal(finished.status,200,JSON.stringify(finished.data));assert.equal(finished.data.state,'ready');
const repeated=await request('/api/generate',{action:'complete',id:generation.id,artifact});assert.equal(repeated.data.modelFile,finished.data.modelFile,'重複完了で別ファイルを作らない');
const stored=await request('/api/files?id='+finished.data.modelFile);assert.deepEqual(stored.data.model,modelData,'骨と部品を正確に保存・復元');
assert.equal((await request('/api/files?id='+finished.data.modelFile,undefined,'')).status,401);
const consumed=await request('/api/generate',{action:'consumed',id:generation.id});assert.equal(consumed.data.state,'consumed');
const cancelled=await request('/api/generate',{...generation,id:crypto.randomUUID()});assert.equal(cancelled.status,200);assert.equal((await request('/api/generate',{action:'cancel',id:cancelled.data.id})).data.state,'cancelled');
assert.equal((await request('/api/generate',{action:'complete',id:cancelled.data.id,artifact})).status,409,'停止した依頼の遅延完了を拒否');
writeFileSync('/private/tmp/dotforge-local-test-records.json',JSON.stringify({projects:[id,id2],asset:asset.id,jobs:[generation.id,cancelled.data.id],file:finished.data.modelFile}));
console.log('HTTP integration passed: auth, immutable revisions, CAS, skill routing, idempotent jobs, artifact persistence, cancellation.');
