import {articulatedReplacement} from '@/lib/sample-models';
import {bindings,owner,readJSON,fail,HttpError,projectOwned} from '@/lib/server';
import {assetSchema,projectSchema} from '@/lib/contracts';
import {validateFrames,type Asset,type Style} from '@/lib/pixel';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const user=await owner(),{db,bucket}=bindings(),url=new URL(request.url);const assetId=url.searchParams.get('assetId');if(assetId){const row=await db.prepare('SELECT object_key,version FROM assets WHERE id=? AND owner=?').bind(assetId,user).first<{object_key:string;version:number}>();if(!row)throw new HttpError(404,'アセットが見つかりません');const object=await bucket.get(row.object_key);if(!object)throw new HttpError(503,'アセットを読み込めませんでした');const asset=await object.json<Asset>();return Response.json({...asset,version:row.version});}
const rows=await db.prepare('SELECT id,name,styles,version,updated_at FROM projects WHERE owner=? ORDER BY updated_at DESC LIMIT 100').bind(user).all<{id:string;name:string;styles:string;version:number;updated_at:string}>();const projects=rows.results.map(r=>({id:r.id,name:r.name,styles:JSON.parse(r.styles),version:r.version,updatedAt:r.updated_at}));const projectId=url.searchParams.get('projectId')||projects[0]?.id;let assets:unknown[]=[];let jobs:unknown[]=[];if(projectId){await projectOwned(projectId,user);assets=(await db.prepare('SELECT id,name,version,updated_at AS updatedAt FROM assets WHERE owner=? AND project_id=? ORDER BY updated_at DESC LIMIT 100').bind(user,projectId).all()).results;jobs=(await db.prepare('SELECT id,state,progress,error,model_file AS modelFile,request,created_at AS createdAt FROM jobs WHERE owner=? AND project_id=? AND dismissed_at IS NULL ORDER BY created_at DESC LIMIT 20').bind(user,projectId).all()).results.map(j=>({...j,request:JSON.parse(j.request as string)}));}return Response.json({projects,assets,jobs},{headers:{'Cache-Control':'no-store'}});}catch(e){return fail(e);}}
export async function POST(request:Request){try{const user=await owner(request),{db,bucket}=bindings();const input=await readJSON(request),now=new Date().toISOString();if(input.action==='project'){
 const p=projectSchema.parse(input.project);const styles=JSON.stringify(p.styles);const existing=await db.prepare('SELECT owner,version,styles FROM projects WHERE id=?').bind(p.id).first<{owner:string;version:number;styles:string}>();if(existing){if(existing.owner!==user)throw new HttpError(404,'プロジェクトが見つかりません');if(existing.version!==p.version)throw new HttpError(409,'別の保存があります。再読み込みしてから変更を反映してください');const old=JSON.parse(existing.styles) as Style[];if(old.some(s=>!p.styles.some(n=>n.id===s.id&&JSON.stringify(n)===JSON.stringify(s))))throw new HttpError(400,'保存済みのスタイル版は変更できません。新版として追加してください');const result=await db.prepare('UPDATE projects SET name=?,styles=?,version=version+1,updated_at=? WHERE id=? AND owner=? AND version=? RETURNING version').bind(p.name,styles,now,p.id,user,p.version).first();if(!result)throw new HttpError(409,'保存が競合しました');return Response.json({...p,version:p.version+1,updatedAt:now});}
 if(p.version!==0)throw new HttpError(409,'プロジェクトを再読み込みしてください');await db.prepare('INSERT INTO projects (id,owner,name,styles,version,updated_at) VALUES (?,?,?,?,1,?)').bind(p.id,user,p.name,styles,now).run();return Response.json({...p,version:1,updatedAt:now});}
 if(input.action==='asset'){
 const a=assetSchema.parse(input.asset);const project=await projectOwned(a.projectId,user);const styles=JSON.parse(project.styles as string) as Style[];for(const r of a.revisions){if(r.parentRevisionId&&!a.revisions.some(parent=>parent.id===r.parentRevisionId&&parent.id!==r.id&&(parent.modelId===r.modelId||(r.source==='sample'&&articulatedReplacement(parent.modelId)?.id===r.modelId))&&parent.modelKey===r.modelKey&&parent.source===r.source))throw new HttpError(400,'共通修正の元の素材版を確認してください');if(!styles.some(s=>s.id===r.style.id&&JSON.stringify(s)===JSON.stringify(r.style)))throw new HttpError(400,'プロジェクトのスタイル版と一致しません');const dataErrors=validateFrames(r.frames,r.style,r.mode).filter(s=>!s.includes('安全範囲')&&!s.includes('余白'));if(dataErrors.length)throw new HttpError(400,dataErrors[0]);if(r.approved&&(!r.reviewed||r.issues.trim()||validateFrames(r.frames,r.style,r.mode).length))throw new HttpError(400,'未解決の確認事項があります');for(const id of [...(r.referenceKeys||[]),...(r.modelKey?[r.modelKey]:[])]){const owned=await db.prepare('SELECT id FROM files WHERE id=? AND owner=?').bind(id,user).first();if(!owned)throw new HttpError(400,'参照ファイルを確認してください');}}
 const old=await db.prepare('SELECT owner,version,object_key,project_id FROM assets WHERE id=?').bind(a.id).first<{owner:string;version:number;object_key:string;project_id:string}>();if(old&&old.project_id!==a.projectId)throw new HttpError(400,'アセットの所属プロジェクトは変更できません');if(old&&(old.owner!==user||old.version!==a.version))throw new HttpError(409,'保存が競合しました。編集内容は残っています');if(!old&&a.version!==0)throw new HttpError(409,'アセットを再読み込みしてください');if(old){const previous=await (await bucket.get(old.object_key))?.json<Asset>();if(!previous)throw new HttpError(503,'修正元の保存状態を読み込めませんでした');const addsSharedCandidate=a.revisions.some(r=>r.sharedEdits&&!previous.revisions.some(p=>p.id===r.id));if(addsSharedCandidate&&previous.revisions.some(r=>!a.revisions.some(n=>n.id===r.id&&JSON.stringify(n)===JSON.stringify(r))))throw new HttpError(400,'新候補の保存時に元の版は変更できません。画面を再読み込みしてから修正してください');if(previous.revisions.some(r=>r.approved&&!a.revisions.some(n=>n.id===r.id&&JSON.stringify(n)===JSON.stringify(r))))throw new HttpError(400,'採用済みの版は上書きできません。候補を複製してください');}
 const key=`${user}/assets/${a.id}/${crypto.randomUUID()}.json`;const saved={...a,version:a.version+1,updatedAt:now};await bucket.put(key,JSON.stringify(saved),{httpMetadata:{contentType:'application/json'}});try{if(old){const result=await db.prepare('UPDATE assets SET name=?,object_key=?,version=version+1,updated_at=? WHERE id=? AND owner=? AND version=? RETURNING id').bind(a.name,key,now,a.id,user,a.version).first();if(!result)throw new HttpError(409,'保存が競合しました');}else await db.prepare('INSERT INTO assets (id,owner,project_id,name,object_key,version,updated_at) VALUES (?,?,?,?,?,1,?)').bind(a.id,user,a.projectId,a.name,key,now).run();}catch(e){await bucket.delete(key);throw e;}return Response.json(saved);}
 throw new HttpError(400,'操作が不明です');}catch(e){return fail(e);}}
