import {bindings,owner,readJSON,fail,HttpError} from '@/lib/server';
import {animationSchema,animationIssues} from '@/lib/animation-contracts';
import type {Asset} from '@/lib/pixel';
import type {AnimationDocument} from '@/lib/animation';
import {animalAnimationSchema,animalAnimationIssues} from '@/lib/animal-contracts';
import {ANIMAL_MOTION_VERSION,type AnimalDocument} from '@/lib/animal-animation';
export const dynamic='force-dynamic';
async function source(assetId:string,user:string){const {db,bucket}=bindings();const row=await db.prepare('SELECT object_key FROM assets WHERE id=? AND owner=?').bind(assetId,user).first<{object_key:string}>();if(!row)throw new HttpError(404,'素材が見つかりません');const object=await bucket.get(row.object_key);if(!object)throw new HttpError(503,'素材を読み込めません');return object.json<Asset>();}
export async function GET(request:Request){try{const user=await owner(),{db,bucket}=bindings(),url=new URL(request.url),id=url.searchParams.get('id');if(id){const row=await db.prepare('SELECT object_key,version FROM animation_sets WHERE id=? AND owner=?').bind(id,user).first<{object_key:string;version:number}>();if(!row)throw new HttpError(404,'アニメーションが見つかりません');const object=await bucket.get(row.object_key);if(!object)throw new HttpError(503,'アニメーションを読み込めません');return Response.json({...await object.json<AnimationDocument|AnimalDocument>(),version:row.version},{headers:{'Cache-Control':'private, no-store'}});}
 const assetId=url.searchParams.get('assetId');if(!assetId)throw new HttpError(400,'素材を指定してください');await source(assetId,user);const rows=await db.prepare('SELECT id,name,source_revision_id AS sourceRevisionId,version,reviewed,updated_at AS updatedAt FROM animation_sets WHERE asset_id=? AND owner=? ORDER BY updated_at DESC LIMIT 100').bind(assetId,user).all();return Response.json({items:rows.results},{headers:{'Cache-Control':'private, no-store'}});
 }catch(error){return fail(error);}}
export async function POST(request:Request){try{const user=await owner(request),{db,bucket}=bindings();const input=await readJSON(request),isAnimal=input.config?.version===ANIMAL_MOTION_VERSION;const doc=isAnimal?animalAnimationSchema.parse(input) as AnimalDocument:animationSchema.parse(input) as AnimationDocument;const asset=await source(doc.assetId,user),revision=asset.revisions.find(r=>r.id===doc.sourceRevisionId);if(!revision)throw new HttpError(400,'元の素材版を確認してください');if(isAnimal!==(revision.rigKind==='quadruped'))throw new HttpError(400,'素材とアニメーションの骨格が一致しません');if(JSON.stringify(doc.config.style)!==JSON.stringify(revision.style)||doc.config.mode!==revision.mode)throw new HttpError(400,'元の素材版のカメラ・色・方向設定と一致しません');
 const issues=isAnimal?animalAnimationIssues(doc as AnimalDocument):animationIssues(doc as AnimationDocument);const blocking=issues.filter(e=>!['安全範囲','余白','届きません','接地'].some(word=>e.includes(word)));if(blocking.length)throw new HttpError(400,blocking[0]);if(doc.reviewed&&(issues.length||doc.baked.some(b=>b.issues.length)))throw new HttpError(400,'全コマの確認事項を解消してください');
 const old=await db.prepare('SELECT owner,asset_id,source_revision_id,version,object_key,reviewed FROM animation_sets WHERE id=?').bind(doc.id).first<{owner:string;asset_id:string;source_revision_id:string;version:number;object_key:string;reviewed:number}>();if(old&&old.owner!==user)throw new HttpError(404,'アニメーションが見つかりません');if(old&&(old.asset_id!==doc.assetId||old.source_revision_id!==doc.sourceRevisionId))throw new HttpError(400,'元の素材版は変更できません');if(old&&old.reviewed)throw new HttpError(400,'採用済みです。新しい候補を作成してください');if((old&&old.version!==doc.version)||(!old&&doc.version!==0))throw new HttpError(409,'別の保存があります。再読込して確認してください');
 const saved={...doc,version:doc.version+1,updatedAt:new Date().toISOString()},key=`${user}/animations/${doc.id}/${crypto.randomUUID()}.json`;await bucket.put(key,JSON.stringify(saved),{httpMetadata:{contentType:'application/json'}});
 try{if(old){const updated=await db.prepare('UPDATE animation_sets SET name=?,object_key=?,version=version+1,reviewed=?,updated_at=? WHERE id=? AND owner=? AND version=? AND reviewed=0 RETURNING id').bind(saved.name,key,saved.reviewed?1:0,saved.updatedAt,saved.id,user,doc.version).first();if(!updated)throw new HttpError(409,'保存が競合しました');}else await db.prepare('INSERT INTO animation_sets (id,owner,asset_id,source_revision_id,name,object_key,version,reviewed,updated_at) VALUES (?,?,?,?,?,?,1,?,?)').bind(saved.id,user,saved.assetId,saved.sourceRevisionId,saved.name,key,saved.reviewed?1:0,saved.updatedAt).run();}catch(error){await bucket.delete(key);throw error;}
 return Response.json(saved);
 }catch(error){return fail(error);}}
