'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Play,Pause,SkipBack,ChevronLeft,ChevronRight,Save,Download,Copy,Check,Loader2,PersonStanding,RotateCcw,KeyRound} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {PixelCanvas} from '@/components/pixel-canvas';
import {MotionGenerationNotice} from '@/components/motion-generation-notice';
import {buildMesh,clone,composite,DIRECTIONS,renderFrame,rotate,type Asset,type Revision,type Mesh,type Direction,type V3} from '@/lib/pixel';
import {BONE_IDS,BONE_NAMES,PARENTS,MOTION_NAMES,MOTION_VERSION,defaultRig,defaultClips,rigFromModel,rigIssues,evaluatePose,poseMesh,unpackFrame,envelopeSkin,sampleKeys,type AnimationDocument,type MotionConfig,type MotionKind,type BoneId,type RiggedModel,type BakedClip} from '@/lib/animation';
import {inheritAnimation,findParentAnimation} from '@/lib/animation-inheritance';
import {animationZip} from '@/lib/animation-export';
import {download} from '@/lib/export';
import {humanoidSample,articulatedReplacement} from '@/lib/sample-models';
import {parseHumanoid,type HumanoidArtifact} from '@/lib/generation';

function Choice({value,onChange,items,label,disabled=false}:{value:string;onChange:(value:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select>;}
function Range({label,value,onChange,min,max,step=1,unit='',disabled=false}:{label:string;value:number;onChange:(value:number)=>void;min:number;max:number;step?:number;unit?:string;disabled?:boolean}){return <div className="motion-range"><label>{label}<output>{Math.round(value*100)/100}{unit}</output></label><Slider aria-label={label} value={[value]} onValueChange={v=>onChange(v[0])} min={min} max={max} step={step} disabled={disabled}/></div>;}
async function request<T>(url:string,body?:unknown):Promise<T>{const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json() as T&{error?:string};if(!response.ok)throw Error(data.error||'保存に失敗しました');return data;}
type Saved={id:string;name:string;sourceRevisionId:string;version:number;reviewed:number};
export function AnimationStudio({open,onClose,asset,revision,loadMesh}:{open:boolean;onClose:()=>void;asset:Asset;revision:Revision;loadMesh:(r:Revision)=>Promise<Mesh>}){
 const [doc,setDoc]=useState<AnimationDocument|null>(null),[mesh,setMesh]=useState<Mesh|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[dirty,setDirty]=useState(false),[saved,setSaved]=useState<Saved[]>([]);
 const [clipId,setClipId]=useState<MotionKind>('walk'),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[direction,setDirection]=useState<Direction>('S'),[bone,setBone]=useState<BoneId>('thighL'),[part,setPart]=useState(''),[isolated,setIsolated]=useState(false),[joints,setJoints]=useState(true),[angles,setAngles]=useState<V3>([0,0,0]),[layer,setLayer]=useState<'body'|'shadow'|'composite'>('composite'),[qualityConfirmed,setQualityConfirmed]=useState(false);
 const worker=useRef<Worker|null>(null),cache=useRef(new Map<string,AnimationDocument>()),demoHistory=useRef(new Map<string,AnimationDocument>()),loaded=useRef(''),liveDoc=useRef(doc);liveDoc.current=doc;
 const key=asset.id+':'+revision.id,isDemo=asset.projectId==='demo';
 useEffect(()=>{if(!open||loaded.current===key)return;let dead=false;setBusy(true);setError('');setPlaying(false);setDoc(null);setMesh(null);setSaved([]);setFrame(0);setDirection('S');
  (async()=>{const model=revision.source==='skill'&&revision.modelKey?parseHumanoid((await request<HumanoidArtifact>('/api/files?id='+revision.modelKey)).model):(revision.source==='sample'?humanoidSample(revision.modelId):undefined);const initialMesh=model&&revision.source==='sample'&&articulatedReplacement(revision.modelId)?buildMesh(model):await loadMesh(revision);let rig=model?rigFromModel(model,revision.source==='skill'?'skill':'sample'):defaultRig();if(!model&&initialMesh.skeleton?.length){const known=initialMesh.skeleton;rig={...rig,origin:'embedded',skinning:'embedded',bones:rig.bones.map(b=>{const found=known.find(k=>k.id===b.id);return found?{...b,pivot:found.pivot}:b;})};}
   const initial:AnimationDocument={id:crypto.randomUUID(),assetId:asset.id,sourceRevisionId:revision.id,name:asset.name.slice(0,93)+' の基本動作',config:{version:MOTION_VERSION,rig,clips:defaultClips(model?.motionCorrections),scale:revision.size,facing:revision.facing,style:clone(revision.style),mode:revision.mode},baked:[],version:0,updatedAt:'',reviewed:false};
   let next=cache.current.get(key)||initial,items:Saved[]=isDemo?[...demoHistory.current.values()].filter(d=>d.assetId===asset.id&&d.sourceRevisionId===revision.id).map(d=>({id:d.id,name:d.name,sourceRevisionId:d.sourceRevisionId,version:d.version,reviewed:d.reviewed?1:0})):[];
   if(!isDemo){const all=(await request<{items:Saved[]}>('/api/animations?assetId='+asset.id)).items;items=all.filter(s=>s.sourceRevisionId===revision.id);if(!cache.current.has(key)){if(items.length)next=await request<AnimationDocument>('/api/animations?id='+items[0].id);else if(revision.parentRevisionId){const parent=findParentAnimation(all,asset.revisions,revision);if(parent){const previous=await request<AnimationDocument>('/api/animations?id='+parent.id);next=inheritAnimation(previous,initial);}}}}
   else if(!cache.current.has(key)&&!items.length&&revision.parentRevisionId){const previous=findParentAnimation([...demoHistory.current.values()].reverse().filter(d=>d.assetId===asset.id),asset.revisions,revision);if(previous)next=inheritAnimation(previous,initial);}
   if(dead)return;setMesh(initialMesh);setDoc(next);setSaved(items);setDirty(false);setQualityConfirmed(false);setPart(initialMesh.parts?.[0]?.id||'');loaded.current=key;
  })().catch(e=>{if(!dead)setError(e.message);}).finally(()=>{if(!dead)setBusy(false);});return()=>{dead=true;};
 },[open,key]);
 useEffect(()=>()=>{worker.current?.terminate();},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const clip=doc?.config.clips.find(c=>c.id===clipId)||doc?.config.clips[0];
 useEffect(()=>{if(!open||!playing||!clip)return;const timer=setInterval(()=>setFrame(f=>{if(f+1>=clip.frames){if(clip.loop)return 0;setPlaying(false);return clip.frames-1;}return f+1;}),1000/clip.fps);return()=>clearInterval(timer);},[playing,open,clip?.fps,clip?.frames,clip?.loop]);
 useEffect(()=>{if(clip)setAngles(clone(sampleKeys(clip,bone,Math.min(frame,clip.frames-1))));},[bone,frame,clip]);
 const prepared=useMemo(()=>mesh&&doc?(doc.config.rig.skinning==='envelope'?envelopeSkin(mesh,doc.config.rig):mesh):null,[mesh,doc?.config.rig]);
 const preview=useMemo(()=>{if(!prepared||!doc||!clip)return null;try{const pose=evaluatePose(doc.config.rig,clip,Math.min(frame,clip.frames-1));const baked=doc.baked.find(b=>b.id===clip.id)?.frames[frame]?.find(f=>f.direction===direction);const image=baked&&!isolated?unpackFrame(baked):renderFrame(poseMesh(prepared,doc.config.rig,pose,isolated?part:undefined),doc.config.style,direction,doc.config.scale,doc.config.facing);return {pose,image,error:''};}catch(e){return {pose:null,image:null,error:e instanceof Error?e.message:'関節を確認してください'};}},[prepared,doc,clip,frame,direction,part,isolated]);
 const rigErrors=useMemo(()=>doc?rigIssues(doc.config.rig,prepared||undefined):[],[doc?.config.rig,prepared]);
 const bakedIssues=doc?.baked.flatMap(b=>b.issues.map(s=>`${MOTION_NAMES[b.id]}: ${s}`))||[];
 const complete=!!doc&&doc.baked.length===doc.config.clips.length&&doc.baked.every(b=>b.frames.length===doc.config.clips.find(c=>c.id===b.id)?.frames);
 const locked=busy||!!doc?.reviewed;
 function change(update:(config:MotionConfig)=>MotionConfig){if(!doc||locked)return;setPlaying(false);setDoc({...doc,config:update(clone(doc.config)),baked:[],reviewed:false});setDirty(true);setQualityConfirmed(false);}
 function changeClip(patch:Partial<NonNullable<typeof clip>>){change(c=>({...c,clips:c.clips.map(old=>old.id===clip?.id?{...old,...patch}:old)}));}
 async function save(adopt=false){if(!doc)return;setBusy(true);setError('');try{const next={...doc,reviewed:adopt};const result=isDemo?{...next,version:next.version+1,updatedAt:new Date().toISOString()}:await request<AnimationDocument>('/api/animations',next);setDoc(result);cache.current.set(key,clone(result));setDirty(false);if(isDemo)demoHistory.current.set(result.id,clone(result));setSaved(list=>[{id:result.id,name:result.name,sourceRevisionId:result.sourceRevisionId,version:result.version,reviewed:result.reviewed?1:0},...list.filter(s=>s.id!==result.id)]);toast.success(isDemo?'この画面内で保持しました':'アニメーションを保存しました');}catch(e){setError(e instanceof Error?e.message:'保存に失敗しました');}finally{setBusy(false);}}
 function bake(){if(!doc||!prepared||locked||rigErrors.length>0||!doc.config.rig.reviewed)return;setBusy(true);setPlaying(false);setError('');setProgress(0);setQualityConfirmed(false);const current=clone(doc);worker.current?.terminate();const task=new Worker(new URL('../lib/animation-worker.ts',import.meta.url),{type:'module'});worker.current=task;task.onmessage=(event:MessageEvent<{type:string;done:number;total:number;baked:BakedClip[];error:string}>)=>{if(worker.current!==task)return;const data=event.data;if(data.type==='progress')setProgress(data.done/data.total);if(data.type==='done'){setDoc({...current,baked:data.baked,reviewed:false});setDirty(true);setBusy(false);task.terminate();worker.current=null;toast.success('全動作・全方向の画素を生成しました');}if(data.type==='error'){setError(data.error);setBusy(false);task.terminate();worker.current=null;}};task.onerror=()=>{if(worker.current!==task)return;setError('生成処理に失敗しました。設定を保持しています');setBusy(false);task.terminate();worker.current=null;};task.postMessage({mesh:prepared,config:current.config});}
 function close(){if(busy){toast.info('処理中です。生成を停止してから閉じてください');return;}if(dirty){toast.info('変更を保存・確定してから閉じてください');return;}setPlaying(false);onClose();}
 function project(point:V3):[number,number]{if(!doc)return [0,0];const p=rotate(point.map(n=>n*doc.config.scale) as V3,[0,0,(DIRECTIONS.indexOf(direction)*45+doc.config.facing)*Math.PI/180]),el=doc.config.style.elevation*Math.PI/180;return [32+p[0]*doc.config.style.scale,52-(p[1]*Math.sin(el)+p[2]*Math.cos(el))*doc.config.style.scale];}
 const selectedBone=doc?.config.rig.bones.find(b=>b.id===bone);
 const directionItems=(revision.mode==='eight'?DIRECTIONS:['S'] as Direction[]).map(d=>({value:d,label:d}));
 return <Dialog open={open} onOpenChange={v=>{if(!v)close();}}><DialogContent className="animation-dialog" onEscapeKeyDown={e=>{if(dirty||busy)e.preventDefault();}} onPointerDownOutside={e=>e.preventDefault()}><DialogHeader className="motion-header"><div><div className="eyebrow">MOTION WORKSPACE</div><DialogTitle>パーツから、動きをつくる</DialogTitle><DialogDescription>{asset.name} · 1コマ64×64 · 共通の関節で全方向を描画</DialogDescription></div><div className="motion-header-actions"><span className="tag">{doc?.reviewed?'採用済み':dirty?'未保存の変更':'候補'}</span><button className="button" disabled={!doc||busy} onClick={()=>{if(doc){const next={...clone(doc),id:crypto.randomUUID(),version:0,reviewed:false,name:doc.name.slice(0,95)+' の候補'};setDoc(next);setDirty(true);setQualityConfirmed(false);}}}><Copy size={15}/>新しい候補</button><button className="button" disabled={!doc||busy||doc.reviewed} onClick={()=>void save()}><Save size={15}/>{isDemo?'変更を確定':'保存'}</button></div></DialogHeader>
 {error&&<div className="motion-error" role="alert">{error}</div>}
 {!doc||!prepared||!clip?<div className="motion-loading">{busy?<><Loader2 className="spin"/>パーツを準備しています</>:<><p>この素材のアニメーションを準備できませんでした。</p><button className="button" onClick={()=>{loaded.current='';onClose();}}>閉じる</button></>}</div>:<>
 <div className="motion-layout"><aside className="motion-parts"><h3><PersonStanding size={17}/> パーツと関節</h3><p className="help">左・右はキャラクター自身の左右です。</p>
 <Choice label="パーツ" value={part||'_none'} onChange={value=>{setPart(value);const attached=doc.config.rig.bindings[value];if(attached)setBone(attached);}} items={prepared.parts?.length?prepared.parts.map(p=>({value:p.id,label:p.name})):[{value:'_none',label:'パーツなし'}]}/>
 <div className="check-row"><Checkbox id="isolate-part" checked={isolated} onCheckedChange={v=>{setIsolated(v===true);setPlaying(false);}}/><label htmlFor="isolate-part">選んだパーツだけ表示</label></div>
 <label className="field-label">このパーツの追従先</label><Choice label="パーツの追従先" value={doc.config.rig.bindings[part]||'_skin'} disabled={locked} onChange={value=>change(c=>{if(value==='_skin')delete c.rig.bindings[part];else c.rig.bindings[part]=value as BoneId;c.rig.reviewed=false;return c;})} items={[{value:'_skin',label:'スキンの重みを使用'},...BONE_IDS.map(id=>({value:id,label:BONE_NAMES[id]}))]}/>
 <div className="bone-tree" aria-label="体の関節">{BONE_IDS.map(id=><button key={id} className={bone===id?'active':''} onClick={()=>{setBone(id);setPlaying(false);}}><i/><span>{BONE_NAMES[id]}</span><small>{doc.config.rig.bones.find(b=>b.id===id)?.parent?BONE_NAMES[PARENTS[id]!]:''}</small></button>)}</div>
 {selectedBone&&<div className="joint-pivot"><h4>{BONE_NAMES[bone]}の支点</h4><p className="help">静止形状上の関節位置。脚は股→膝→足首を合わせます。</p>{(['X 左右','Y 前後','Z 高さ'] as const).map((label,i)=><label key={label}>{label}<input type="number" aria-label={`${BONE_NAMES[bone]} ${label}`} step="0.01" min="-5" max="5" value={selectedBone.pivot[i]} disabled={locked} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&Math.abs(n)<=5)change(c=>{c.rig.bones=c.rig.bones.map(b=>b.id===bone?{...b,pivot:b.pivot.map((v,j)=>j===i?n:v) as V3}:b);c.rig.reviewed=false;return c;});}}/></label>)}</div>}
 {doc.config.rig.origin!=='sample'&&<div className="motion-import-note"><p className="help">骨格のない人型は、正面・手足の位置を合わせて推定割当できます。衣装や持ち物は追従先を確認してください。</p><button className="button full" disabled={locked} onClick={()=>change(c=>{c.rig={...c.rig,skinning:'envelope',origin:'manual',bindings:{},reviewed:false};setPart('region-pelvis');return c;})}>人型の部位を推定する</button>{doc.config.rig.skinning==='envelope'&&<p className="notice">推定割当です。細い部位・衣装・腕を広げた姿勢は支点や重みの調整が必要です。</p>}</div>}

 </aside><main className="motion-main"><div className="motion-tabs" role="group" aria-label="動作">{doc.config.clips.map(c=><button key={c.id} className={clip.id===c.id?'active':''} onClick={()=>{setClipId(c.id);setFrame(0);setPlaying(false);}}><span>{c.name}</span><small>{c.frames}コマ / {c.loop?'ループ':'単発'}</small></button>)}</div>
 <p className="help">共通の3D形状から動きを作ります。静止画への1ピクセルの手修正は、自動では引き継がれません。</p><div className="motion-preview-tools"><Choice label="アニメーション方向" value={direction} onChange={v=>setDirection(v as Direction)} items={directionItems}/><Choice label="アニメーションのレイヤー" value={layer} onChange={v=>setLayer(v as typeof layer)} items={[{value:'composite',label:'物体＋影'},{value:'body',label:'物体'},{value:'shadow',label:'影'}]}/><div className="check-row"><Checkbox id="show-joints" checked={joints} onCheckedChange={v=>setJoints(v===true)}/><label htmlFor="show-joints">関節</label></div></div>
 <div className="motion-preview-stage"><div className="motion-canvas">{preview?.image&&<PixelCanvas pixels={composite(preview.image,layer)} palette={doc.config.style.palette} scale={5} label={`${clip.name} ${direction} ${frame+1}コマ`}/>} {joints&&preview?.pose&&<svg viewBox="0 0 64 64" className="joint-overlay" aria-label="関節と骨の位置">{BONE_IDS.map(id=>{const p=preview.pose!.bones[id],xy=project(p.position),parent=PARENTS[id],parentXY=parent?project(preview.pose!.bones[parent].position):null;return <g key={id}>{parentXY&&<line x1={parentXY[0]} y1={parentXY[1]} x2={xy[0]} y2={xy[1]}/>}<circle className={id===bone?'selected':''} cx={xy[0]} cy={xy[1]} r={id===bone?1.15:.65}/></g>;})}</svg>}</div>{preview?.error&&<p role="alert">{preview.error}</p>}<div className="contact-badges"><span className={preview?.pose?.contacts.left?'planted':''}>左足 {preview?.pose?.contacts.left?'接地':'空中'}</span><span className={preview?.pose?.contacts.right?'planted':''}>右足 {preview?.pose?.contacts.right?'接地':'空中'}</span></div></div>
 <div className="motion-playbar"><button className="tool" aria-label="先頭へ" onClick={()=>{setPlaying(false);setFrame(0);}}><SkipBack size={17}/></button><button className="tool" aria-label="前のコマ" onClick={()=>{setPlaying(false);setFrame(f=>Math.max(0,f-1));}}><ChevronLeft size={18}/></button><button className="button primary" disabled={!!preview?.error} onClick={()=>{if(!playing&&frame===clip.frames-1)setFrame(0);setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'停止':'再生'}</button><button className="tool" aria-label="次のコマ" onClick={()=>{setPlaying(false);setFrame(f=>Math.min(clip.frames-1,f+1));}}><ChevronRight size={18}/></button><output>{frame+1} / {clip.frames}</output><span>{clip.fps} fps · {(clip.frames/clip.fps).toFixed(2)}秒</span></div>
 <div className="motion-timeline" aria-label="アニメーションのコマ">{Array.from({length:clip.frames},(_,i)=><button key={i} aria-label={`${i+1}コマへ移動`} aria-pressed={frame===i} className={frame===i?'active':''} onClick={()=>{setPlaying(false);setFrame(i);}}><span>{String(i+1).padStart(2,'0')}</span>{clip.keys[bone]?.some(k=>k.frame===i)?<KeyRound size={13}/>:<i/>}</button>)}</div>
 <p className="timeline-caption">{BONE_NAMES[bone]}の関節キー · {clip.id==='walk'?'その場歩行。ゲーム側の推奨移動速度をJSONへ出力します。':clip.id==='jump'?'予備動作 → 離陸 → 頂点 → 着地 → 復帰':clip.id==='crouch'?'下げる → 保持 → 戻る':'同じ姿勢から静かな上下動を作ります。'}</p>
 {preview?.pose?.issues.length? <p className="notice">{preview.pose.issues[0]}</p>:null}
 <MotionGenerationNotice id="humanoid-generation-notice" busy={busy} adopted={doc.reviewed} rigReviewed={doc.config.rig.reviewed} rigErrors={rigErrors} onReview={reviewed=>change(c=>({...c,rig:{...c.rig,reviewed}}))}/>
 <div className="motion-quality"><div><strong>{complete?'全コマを生成済み':'プレビュー中'}</strong><span>{complete?`${doc.baked.reduce((n,b)=>n+b.frames.length,0)}コマ × ${revision.mode==='eight'?8:1}方向 / ${bakedIssues.length}件の確認事項`:'設定を確認して全動作を生成してください'}</span></div>{busy&&worker.current?<><progress value={progress} max={1}/><button className="text-button" onClick={()=>{if(worker.current){worker.current.onmessage=null;worker.current.onerror=null;worker.current.terminate();}worker.current=null;setBusy(false);setError('生成を停止しました。設定は保持しています');}}>生成を停止</button></>:<button className="button primary" aria-describedby="humanoid-generation-notice" disabled={locked||rigErrors.length>0||!doc.config.rig.reviewed} onClick={bake}><RotateCcw size={16}/>全動作・全方向を生成</button>}</div>
 {bakedIssues.length>0&&<details className="motion-issues"><summary>確認事項を表示（{bakedIssues.length}件）</summary><ul>{bakedIssues.slice(0,40).map((s,i)=><li key={i}>{s}</li>)}</ul></details>}
 </main><aside className="motion-settings"><h3>動きの設定</h3><Range label="フレーム数" value={clip.frames} min={4} max={24} onChange={v=>{setFrame(0);changeClip({frames:v,keys:Object.fromEntries(Object.entries(clip.keys).map(([id,keys])=>[id,keys?.filter(k=>k.frame<v)]))});}} disabled={locked}/><Range label="再生速度" value={clip.fps} min={4} max={24} unit=" fps" onChange={v=>changeClip({fps:v})} disabled={locked}/>
 {clip.id==='walk'&&<><Range label="歩幅" value={clip.stride} min={0} max={.8} step={.01} onChange={v=>changeClip({stride:v})} disabled={locked}/><Range label="足の上げ幅" value={clip.lift} min={0} max={.4} step={.01} onChange={v=>changeClip({lift:v})} disabled={locked}/><Range label="腕振り" value={clip.armSwing} min={0} max={70} unit="°" onChange={v=>changeClip({armSwing:v})} disabled={locked}/></>}
 {(clip.id==='crouch'||clip.id==='jump')&&<Range label={clip.id==='crouch'?'しゃがむ深さ':'踏み込みの深さ'} value={clip.depth} min={0} max={.5} step={.01} onChange={v=>changeClip({depth:v})} disabled={locked}/>}
 {clip.id==='crouch'&&<Range label="低い姿勢を保つ割合" value={clip.hold} min={.1} max={.7} step={.05} onChange={v=>changeClip({hold:v})} disabled={locked}/>}
 {clip.id==='jump'&&<Range label="ジャンプの高さ" value={clip.height} min={0} max={.8} step={.01} onChange={v=>changeClip({height:v})} disabled={locked}/>}
 <div className="motion-joint-keys"><h4>{BONE_NAMES[bone]}の回転補正</h4><p className="help">{frame+1}コマにキーを追加します。子の部位と装備も一緒に動きます。</p>{['前後','左右','ひねり'].map((label,i)=><Range key={label} label={label} value={angles[i]} min={-90} max={90} unit="°" onChange={v=>{setPlaying(false);setAngles(a=>a.map((n,j)=>j===i?v:n) as V3);}} disabled={locked}/>)}<button className="button full" disabled={locked} onClick={()=>changeClip({keys:{...clip.keys,[bone]:[...(clip.keys[bone]||[]).filter(k=>k.frame!==frame),{frame,rotation:angles}].sort((a,b)=>a.frame-b.frame)}})}><KeyRound size={15}/>このコマに関節キーを設定</button><button className="text-button full-text" disabled={locked||!clip.keys[bone]?.some(k=>k.frame===frame)} onClick={()=>changeClip({keys:{...clip.keys,[bone]:clip.keys[bone]?.filter(k=>k.frame!==frame)}})}>このコマのキーを解除</button></div>
 <div className="motion-size"><h4>64×64への収まり</h4><Range label="全動作共通のサイズ" value={doc.config.scale} min={.1} max={2} step={.05} onChange={v=>change(c=>({...c,scale:v}))} disabled={locked}/><p className="help">枠を超えるときは全動作を同じ比率で縮めます。方向・コマごとの自動拡縮は行いません。</p></div>
 <div className="motion-export"><h4>確認と書き出し</h4><p className="help">左右の装備、足の接地、全方向の関節、衣装の重なりを確認してください。</p><div className="check-row"><Checkbox id="motion-quality" checked={qualityConfirmed||doc.reviewed} onCheckedChange={v=>setQualityConfirmed(v===true)} disabled={!complete||busy||doc.reviewed||bakedIssues.length>0}/><label htmlFor="motion-quality">全動作・全方向を確認した</label></div><button className="button full" disabled={!complete||bakedIssues.length>0||!qualityConfirmed||busy||doc.reviewed} onClick={()=>void save(true)}><Check size={15}/>このアニメーションを採用</button><button className="button primary full" disabled={!complete||busy||bakedIssues.length>0} onClick={()=>{try{download(animationZip(doc,layer),`${asset.name}-animations${doc.reviewed?'':'-draft'}.zip`,'application/zip');}catch(e){setError(e instanceof Error?e.message:'出力に失敗しました');}}}><Download size={16}/>PNGシート＋JSON</button><p className="help">横＝時間、縦＝方向。各セル64×64。関節の表示は書き出しません。</p></div>
 </aside></div><footer className="motion-footer"><span>{doc.config.rig.origin==='sample'?'部位分割済みサンプル':doc.config.rig.skinning==='envelope'?'推定した人型の重み':'持ち込みモデルの部位'} · {prepared.parts?.length||0}パーツ · 16関節</span>{saved.length>0&&<Choice label="保存済みアニメーション" value={saved.some(s=>s.id===doc.id)?doc.id:'_draft'} items={[...(!saved.some(s=>s.id===doc.id)?[{value:'_draft',label:'編集中の候補'}]:[]),...saved.map(s=>({value:s.id,label:`${s.name} · ${s.reviewed?'採用済み':'候補'}`}))]} disabled={busy||dirty} onChange={id=>{setBusy(true);(isDemo?Promise.resolve(clone(demoHistory.current.get(id)!)):request<AnimationDocument>('/api/animations?id='+id)).then(next=>{setDoc(next);setFrame(0);setPlaying(false);setDirty(false);setQualityConfirmed(false);cache.current.set(key,clone(next));}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}/>}<button className="text-button" disabled={busy} onClick={()=>{loaded.current='';setDoc(null);setDirty(false);setPlaying(false);onClose();}}>変更を破棄して閉じる</button><span>{isDemo?'確定した変更はこの画面内だけで保持されます':'元の静止画は保持されます'}</span></footer>
 </>}
 </DialogContent></Dialog>;
}
