import * as THREE from 'three';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import type {Mesh,Triangle,Texture,V3} from './pixel';
export async function loadGLB(url:string):Promise<Mesh>{const response=await fetch(url);if(!response.ok)throw Error('モデルを取得できません');const bytes=await response.arrayBuffer();if(bytes.byteLength>25*1024*1024)throw Error('モデルは25MB以下にしてください');const header=new DataView(bytes);if(header.getUint32(0,true)!==0x46546c67)throw Error('GLB形式ではありません');const jsonLength=header.getUint32(12,true);const json=JSON.parse(new TextDecoder().decode(bytes.slice(20,20+jsonLength)));if([...(json.buffers||[]),...(json.images||[])].some((v:{uri?:string})=>v.uri&&!v.uri.startsWith('data:')))throw Error('外部ファイルを含むモデルには対応していません');if(json.extensionsRequired?.some((e:string)=>['KHR_texture_basisu'].includes(e)))throw Error('圧縮を解除したGLBを使用してください');
 const draco=new DRACOLoader().setDecoderPath('/decoders/');const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).setDRACOLoader(draco);const gltf=await loader.parseAsync(bytes,'');draco.dispose();gltf.scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(gltf.scene),center=box.getCenter(new THREE.Vector3()),height=box.max.y-box.min.y;if(!Number.isFinite(height)||height<=0)throw Error('モデルのサイズを確認できません');const factor=2.35/height,triangles:Triangle[]=[],textures:Record<string,Texture>={};const world=(v:THREE.Vector3):V3=>[(v.x-center.x)*factor,-(v.z-center.z)*factor,(v.y-box.min.y)*factor];let count=0;
 try{gltf.scene.traverse(obj=>{if(!(obj instanceof THREE.Mesh))return;const geo=obj.geometry,pos=geo.attributes.position,uv=geo.attributes.uv,index=geo.index,materials=Array.isArray(obj.material)?obj.material:[obj.material];if(!pos)return;const vertexCount=index?index.count:pos.count;count+=vertexCount/3;if(count>60000)throw Error('60,000面以下のモデルを使用してください');for(let i=0;i<vertexCount;i+=3){const group=geo.groups.find((g:{start:number;count:number;materialIndex?:number})=>i>=g.start&&i<g.start+g.count);const mat=materials[group?.materialIndex||0] as THREE.MeshStandardMaterial;if(mat.visible===false||mat.opacity<.5)continue;let texture:string|undefined;if(mat.map?.image){texture=mat.map.uuid;if(!textures[texture]){const image=mat.map.image as CanvasImageSource&{width:number;height:number},w=Math.min(1024,image.width),h=Math.min(1024,image.height);if(w*h>0){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(ctx){ctx.drawImage(image,0,0,w,h);textures[texture]={width:w,height:h,data:ctx.getImageData(0,0,w,h).data};}}}}
 const ids=[0,1,2].map(n=>index?index.getX(i+n):i+n);const vertices=ids.map(j=>world(new THREE.Vector3().fromBufferAttribute(pos,j).applyMatrix4(obj.matrixWorld))) as [V3,V3,V3];const coords=uv?ids.map(j=>{const v=new THREE.Vector2(uv.getX(j),uv.getY(j));if(mat.map)mat.map.transformUv(v);return [v.x,v.y] as [number,number];}) as Triangle['uv']:undefined;triangles.push({vertices,color:'#'+(mat.color?.getHexString(THREE.SRGBColorSpace)||'ffffff'),texture,uv:coords});}});if(!triangles.length)throw Error('モデルに描画できる形状がありません');return {triangles,textures};}finally{gltf.scene.traverse(obj=>{if(obj instanceof THREE.Mesh){obj.geometry.dispose();const materials=Array.isArray(obj.material)?obj.material:[obj.material];materials.forEach(m=>{const map=(m as THREE.MeshStandardMaterial).map;map?.dispose();m.dispose();});}});}}
