import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export class ProviderRejected extends HttpError{}
export function bindings(){if(!env.DB||!env.BUCKET)throw new HttpError(503,'保存先を準備中です。入力内容はそのままお待ちください。');return {db:env.DB,bucket:env.BUCKET};}
export async function owner(request?:Request){const user=await getChatGPTUser();if(!user)throw new HttpError(401,'ログインが必要です');if(request&&request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new HttpError(403,'この操作は制作画面から行ってください');}return user.userId;}
export async function readJSON(request:Request,max=8*1024*1024){if(Number(request.headers.get('content-length')||0)>max)throw new HttpError(413,'保存できる容量を超えています');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'入力がありません');let size=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new HttpError(413,'保存できる容量を超えています');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new HttpError(400,'入力の形式が正しくありません');}}
export function fail(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});if(error&&typeof error==='object'&&'issues' in error)return Response.json({error:'入力内容の形式または上限を確認してください'},{status:400});console.error('Studio request failed',error instanceof Error?error.message:'unknown');return Response.json({error:'保存・取得に失敗しました。内容を保持したまま再試行できます。'},{status:500});}
export async function projectOwned(id:string,user:string){const {db}=bindings();const row=await db.prepare('SELECT * FROM projects WHERE id=? AND owner=?').bind(id,user).first();if(!row)throw new HttpError(404,'プロジェクトが見つかりません');return row;}
export function providerKey(){return (env as Cloudflare.Env&{TRIPO_API_KEY?:string}).TRIPO_API_KEY;}
export async function tripo(path:string,init:RequestInit={}){const key=providerKey();if(!key)throw new HttpError(503,'AI生成の接続設定が必要です。サンプルと持ち込みモデルは利用できます。');const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${key}`);if(typeof init.body==='string')headers.set('Content-Type','application/json');const response=await fetch(`https://api.tripo3d.ai/v2/openapi${path}`,{...init,headers,signal:AbortSignal.timeout(45000)});if(!response.ok){if(response.status>=400&&response.status<500)throw new ProviderRejected(502,`生成サービスが入力を拒否しました（${response.status}）`);throw new HttpError(502,`生成サービスに接続できませんでした（${response.status}）`);}const result=await response.json() as {code:number;data:Record<string,unknown>};if(result.code!==0)throw new ProviderRejected(502,'生成サービスがリクエストを受け付けませんでした');return result.data;}
