import {bindings,owner,readJSON,fail,HttpError,projectOwned,tripo,ProviderRejected} from '@/lib/server';
import {generationSchema} from '@/lib/contracts';
export const dynamic='force-dynamic';
const MODEL='P1-20260311';
type Job={id:string;owner:string;project_id:string;request:string;state:string;task_id:string|null;model_file:string|null;progress:number;credits:number|null;error:string|null;created_at:string;updated_at:string};
const publicJob=(j:Job)=>({id:j.id,state:j.state,modelFile:j.model_file,progress:j.progress,credits:j.credits,error:j.error,request:JSON.parse(j.request),createdAt:j.created_at});
export async function POST(request:Request){try{const user=await owner(request),{db,bucket}=bindings(),input=await readJSON(request,20000);if(input.action==='cancel'){const job=await db.prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(input.id,user).first<Job>();if(!job)throw new HttpError(404,'ジョブが見つかりません');await db.prepare('UPDATE jobs SET state=?,error=?,updated_at=? WHERE id=? AND owner=?').bind('paused','画面上の監視を停止しました。提供元で開始済みの処理・課金は停止されません。',new Date().toISOString(),job.id,user).run();return Response.json({id:job.id,state:'paused'});}
 const body=generationSchema.parse(input);const ownedProject=await projectOwned(body.projectId,user);if(!(JSON.parse(ownedProject.styles as string) as unknown[]).some(s=>JSON.stringify(s)===JSON.stringify(body.style)))throw new HttpError(400,'保存済みのプロジェクトスタイルを選択してください');const existing=await db.prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(body.id,user).first<Job>();if(existing)return Response.json(publicJob(existing));const running=await db.prepare("SELECT id FROM jobs WHERE owner=? AND state IN ('submitting','queued','running','downloading','paused','uncertain','download_error') LIMIT 1").bind(user).first();if(running)throw new HttpError(409,'進行中の生成があります。完了または状態確認を待ってください');if(body.referenceKeys.length!==body.referenceSides.length||new Set(body.referenceSides).size!==body.referenceSides.length||(body.referenceKeys.length&&!body.referenceSides.includes('front')))throw new HttpError(400,'参照の方向を重複なく指定し、正面を含めてください');
 const estimate=body.referenceKeys.length?50:40;if(body.maxCredits<estimate)throw new HttpError(400,`この生成の見積は${estimate} creditsです。上限を確認してください`);const balance=await tripo('/user/balance');if(typeof balance.balance==='number'&&balance.balance<estimate)throw new HttpError(400,'生成サービスの残高が不足しています');const prompt=`${body.prompt}\nRequired identity features: ${body.features.join('; ')}\nSingle complete low-poly game asset, neutral static pose, plain albedo colors, no baked lighting or ground, coherent back and side design.`;if(prompt.length>1024)throw new HttpError(400,'説明と保持する特徴を合わせて短くしてください');
 const now=new Date().toISOString();await db.prepare('INSERT INTO jobs (id,owner,project_id,request,state,progress,created_at,updated_at) VALUES (?,?,?,?,?,0,?,?)').bind(body.id,user,body.projectId,JSON.stringify({...body,model:MODEL,estimatedCredits:estimate}),'submitting',now,now).run();let payload:Record<string,unknown>={type:'text_to_model',prompt,model_version:MODEL,face_limit:5000,texture:true,pbr:true,texture_quality:'standard'};let submissionStarted=false;let acceptedTaskId:string|null=null;try{if(body.referenceKeys.length){const uploadedFiles:Record<string,{type:string;file_token:string}>={};for(let i=0;i<body.referenceKeys.length;i++){const file=await db.prepare('SELECT object_key,kind FROM files WHERE id=? AND owner=?').bind(body.referenceKeys[i],user).first<{object_key:string;kind:string}>();if(!file||!file.kind.startsWith('image/'))throw new HttpError(400,'参照画像を確認してください');const object=await bucket.get(file.object_key);if(!object)throw new HttpError(404,'参照画像がありません');const type=file.kind==='image/jpeg'?'jpg':file.kind.split('/')[1];const form=new FormData();form.append('file',new Blob([await object.arrayBuffer()],{type:file.kind}),'reference.'+type);const uploaded=await tripo('/upload/sts',{method:'POST',body:form});if(typeof uploaded.image_token!=='string')throw new HttpError(502,'参照画像を送信できませんでした');uploadedFiles[body.referenceSides[i]]={type,file_token:uploaded.image_token};}payload={type:body.referenceKeys.length>1?'multiview_to_model':'image_to_model',...(body.referenceKeys.length>1?{files:['front','left','back','right'].map(side=>uploadedFiles[side]||{})}:{file:uploadedFiles.front}),model_version:MODEL,face_limit:5000,texture:true,pbr:true,texture_quality:'standard',texture_alignment:'geometry',orientation:'align_image'};}
 submissionStarted=true;const result=await tripo('/task',{method:'POST',body:JSON.stringify(payload)});if(typeof result.task_id!=='string')throw new HttpError(502,'生成受付を確認できませんでした');acceptedTaskId=result.task_id;await db.prepare('UPDATE jobs SET task_id=?,state=?,updated_at=? WHERE id=?').bind(result.task_id,'queued',new Date().toISOString(),body.id).run();return Response.json({id:body.id,state:'queued',progress:0});}catch(error){const uncertain=submissionStarted&&!(error instanceof ProviderRejected);await db.prepare('UPDATE jobs SET state=?,task_id=?,error=?,updated_at=? WHERE id=?').bind(uncertain?'uncertain':'failed',acceptedTaskId,uncertain?'生成の受付結果を確認できません。二重課金を避けるため自動再送しません。提供元の履歴を確認してください。':'生成開始前に失敗しました。入力を修正して再試行できます。',new Date().toISOString(),body.id).run();throw error;}
 }catch(e){return fail(e);}}
export async function GET(request:Request){try{const user=await owner(),{db,bucket}=bindings(),id=new URL(request.url).searchParams.get('id');const job=await db.prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(id,user).first<Job>();if(!job)throw new HttpError(404,'ジョブが見つかりません');if(!job.task_id||['ready','failed','consumed'].includes(job.state))return Response.json(publicJob(job));const data=await tripo(`/task/${encodeURIComponent(job.task_id)}`);const state=String(data.status);let modelFile=job.model_file;let error:string|null=null;let resultState=state;
 if(state==='success'&&!modelFile){const output=data.output as Record<string,unknown>|undefined;const url=output?.pbr_model||output?.model||output?.base_model;if(typeof url!=='string'||!url.startsWith('https://'))throw new HttpError(502,'生成モデルの取得先が見つかりません');const lock=await db.prepare("UPDATE jobs SET state='downloading',updated_at=? WHERE id=? AND (state!='downloading' OR updated_at<?) RETURNING id").bind(new Date().toISOString(),job.id,new Date(Date.now()-120000).toISOString()).first();if(!lock)return Response.json({...publicJob(job),state:'downloading'});
 try{const response=await fetch(url,{signal:AbortSignal.timeout(60000),redirect:'error'});if(!response.ok||!response.body)throw new HttpError(502,'生成モデルを取得できませんでした');const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>25*1024*1024){await reader.cancel();throw new HttpError(413,'生成モデルが25MBを超えています。低ポリ設定で作り直してください');}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.length;}if(String.fromCharCode(...bytes.slice(0,4))!=='glTF')throw new HttpError(502,'取得したモデルがGLBではありません');modelFile=crypto.randomUUID();const key=`${user}/files/${modelFile}`;await bucket.put(key,bytes,{httpMetadata:{contentType:'model/gltf-binary'}});await db.prepare('INSERT INTO files (id,owner,name,kind,object_key,size,created_at) VALUES (?,?,?,?,?,?,?)').bind(modelFile,user,'generated.glb','model/gltf-binary',key,size,new Date().toISOString()).run();resultState='ready';}catch(e){await db.prepare("UPDATE jobs SET state='download_error',error=?,updated_at=? WHERE id=?").bind('モデルの保存に失敗しました。状態更新で取得を再試行できます。',new Date().toISOString(),job.id).run();throw e;}}
 if(modelFile)resultState='ready';if(['failed','banned','expired','cancelled','unknown'].includes(state)){resultState='failed';error='生成サービスで完了できませんでした。内容を見直して、新しい生成を開始してください。';}const progress=typeof data.progress==='number'?Math.round(data.progress):0,credits=typeof data.consumed_credit==='number'?data.consumed_credit:null;await db.prepare('UPDATE jobs SET state=?,model_file=?,progress=?,credits=?,error=?,updated_at=? WHERE id=?').bind(resultState,modelFile,progress,credits,error,new Date().toISOString(),job.id).run();return Response.json({...publicJob(job),state:resultState,modelFile,progress,credits,error});}catch(e){return fail(e);}}
